create schema schedule;
USE schedule;


CREATE TABLE AUTHOR(
                       ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '작성 식별자',
                       NAME VARCHAR(30) NOT NULL COMMENT '이름',
                       EMAIL VARCHAR(100) NOT NULL COMMENT '메일',
                       CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
                       UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);

CREATE TABLE SCHEDULE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정관리 식별자' ,
    AUTHOR_ID BIGINT NOT NULL COMMENT '작성자 ID' ,
    TITLE VARCHAR(100) NOT NULL COMMENT '제목' ,
    CONTENTS TEXT COMMENT '내용',
    PASSWORD VARCHAR(50) NOT NULL COMMENT '비밀번호',
    IS_DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '삭제 여부 (0: 활성, 1 : 삭제)' ,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '등록일',
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일',
    CONSTRAINT FK_SCHEDULE_AUTHOR
        FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE
);