create schema schedule;
USE schedule;

CREATE TABLE SCHEDULE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '일정관리 식별자' ,
    AUTHOR VARCHAR(20) NOT NULL COMMENT '작성자' ,
    TITLE VARCHAR(100) NOT NULL COMMENT '제목' ,
    CONTENTS TEXT COMMENT '내용',
    PASSWORD VARCHAR(50) NOT NULL COMMENT '비밀번호',
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    UPDATE_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);